# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\git\PyDigits_RealTimeHandWriteRecog\ui\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(858, 667)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_painter = QtWidgets.QLabel(self.centralwidget)
        self.label_painter.setGeometry(QtCore.QRect(30, 30, 560, 560))
        self.label_painter.setObjectName("label_painter")
        self.pushButton_clearPainter = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_clearPainter.setGeometry(QtCore.QRect(640, 80, 101, 28))
        self.pushButton_clearPainter.setObjectName("pushButton_clearPainter")
        self.label_result = QtWidgets.QLabel(self.centralwidget)
        self.label_result.setGeometry(QtCore.QRect(640, 140, 201, 41))
        self.label_result.setObjectName("label_result")
        self.pushButton_startWrite = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_startWrite.setGeometry(QtCore.QRect(640, 20, 101, 28))
        self.pushButton_startWrite.setObjectName("pushButton_startWrite")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 858, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_painter.setText(_translate("MainWindow", "绘图板"))
        self.pushButton_clearPainter.setText(_translate("MainWindow", "清屏"))
        self.label_result.setText(_translate("MainWindow", "识别结果："))
        self.pushButton_startWrite.setText(_translate("MainWindow", "开始手写数字"))
